GET http://localhost:3232

###


GET http://localhost:3232/routes/

###

GET http://localhost:3232/pathfind/124.64405905455351 8.476703511625551/124.65731352567673 8.48160439674907

###
GET http://localhost:3232/test/


###

POST http://localhost:3232/pathfind/124.64405905455351 8.476703511625551/124.65731352567673 8.48159113237676


###
GET http://cdopuv.org/itineraries?origin=124.62075233459474 8.505224863792407&destination=124.64272499084474 8.48188029558921

###
GET http://localhost:8080/withpoints

###
GET http://localhost:3232/admin/routes

###
GET http://localhost:3232/admin/reports
###
POST http://localhost:8080/signup
Content-Type: application/json

{
    "username": "axis2",
    "password": "password1"
}

###

POST http://localhost:8080/login
Content-Type: application/json

{
    "username": "axis",
    "password": "password1"
}

###
GET http://localhost:8080/admin

###
GET http://localhost:8080/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.YXhpcw.PSGBawPhnN0iGnsak0bM6FtuwltJnGEmyYnX_XRQPk8

SELECT * FROM routes where ST_Distance(ST_Transform(st_setsrid(st_makepoint(<dest longitude>, dest.latitude),4326),3857) < 300 order by <-> the_geom